### ISSUE TITLE
Some issues with the new version

### ISSUE THREAD

**Issue by gordonrix** [christopher-vollmers/C3POa#3]
Hello! I have been happily using the old branch that you had made for me (peakFinderSettings) for a while now, but wanted to see if I could get updated to the newer version. I've managed to get it to work, but I've come across a couple issues. All were fixable by modifying the C3POa.py file. I have uploaded my version of the file to 

https://github.com/gordonrix/maple/blob/main/rules/utils/C3POa.py

Basically I'm just moving the C3POa directory into the lib/python3.9 folder of my conda environment and swapping out the C3POa.py from your directory with the one from mine, and it's working fine now. These are the changes I have made:

1. Lines 62 and 93. add in peakFinderSettings argument. No different than what you had done before, works well.
2. Line 213, add list initialization. This fixes a bug that I believe results from moving list initialization into a function that is called when the input is a directory but not called when the path is a file. I strictly use this tool on individual files, it allows my pipeline to be more modular with respect to whether this consensus or another or no consensus program is used.
3. Lines 20 and 21. Removed `C3POaPath` prepending racon and blat binaries. I am using conda to install these so they are available in my $PATH. I think the previous way the paths for these were determined was more versatile, so switching back to that would be good and would allow the user to use conda to install most dependencies other than conk.

One thing I didn't understand is that I did not need to install abpoa in order to get this to work. Everything is working perfectly well but abpoa is not available in my $PATH and is not found in the location where it should be based on line 19. When should that package be used? Wondering if the current state is fine or if I should be concerned at all

Another comment I have is just that I liked the tqdm progress bar. The time remaining doesn't seem to be working well when it's just one file

**Comment by christopher-vollmers** [comment]
Hi Gordon,

Added the peakfinder setting. Give it a try.

The newest version really changed how input is handled (hence the bug). It
now goes file by file because combined input files were just getting too
big (up to a TB) so we just point it at the pass/ folder. This version will
be slower when pointed at a big file because we no longer multithread the
blat adapter finding. The I/O of making multiple files for multithreading
took more time than just running it once. Is there a reason to prefer
running it on individual files?

For me, conda has always been more trouble than actual benefit and my
former graduate student was a lot more familiar with it which is why I
stopped supporting it.
The C3POaPath thing comes from the setup.sh script now (hopefully)
installing all dependencies into the C3POa folder. I was hoping to make it
easier this way if there are other versions of these programs in path.

Are you sure it's just running without abpoa? the setup.sh script should
put it in the C3POa directory. Did you just replace C3POa.py or pull the
whole repo?
C3POa should straight up fail without abpoa.

Best,
Chris

**Comment by christopher-vollmers** [comment]
What does the abpoa.messages file look like? should be in the folder you
run c2poa from

**Comment by gordonrix** [comment]
Thanks for the quick reply! That file says:

`sh: 1: /home/popos/mambaforge/envs/maple/lib/python3.9//abPOA-v1.4.1/bin/abpoa: not found`

But my output looks pretty normal I think.

I'll probably move back to the old version if you're no longer supporting conda or multiprocessing of single file inputs. I already have a framework that relies on single file inputs. I could probably rework my pipeline around the new version but I don't have the time right now. I think enforcing numpy <1.2 should allow me to use the old version

**Comment by gordonrix** [comment]
FYI if you are trying to figure out what is going on with the abpoa not being needed, the way that I am setting up the environment is to run these commands in my conda directory after building the environment:

```
        mkdir -p src && cd src
        if [ -d C3POa ]; then
            rm -r -f C3POa
        fi
        git clone https://github.com/christopher-vollmers/C3POa.git

        if [ -d conk ]; then
            rm -r -f conk
        fi
        git clone https://github.com/rvolden/conk && cd conk
        python setup.py sdist bdist_wheel
        python -m pip install dist/conk*whl --force-reinstall
        cd ../..
        rm -r -f src/conk
        
        if [ -d lib/python3.9/bin ]; then
            mv src/C3POa/bin/* lib/python3.9/bin/
        else
            mv src/C3POa/bin lib/python3.9
        fi
        mv src/C3POa/C3POa.py src/C3POa/C3POa_postprocessing.py lib/python3.9
        rm -r -f src/C3POa
        
        # need custom peak finder settings so until this is fixed, use the one from the maple repo
        cd src
        if [ -d maple_alt ]; then
            rm -r -f conk
        fi
        git clone https://github.com/gordonrix/maple.git maple_alt && cd ..
        mv src/maple_alt/rules/utils/C3POa.py lib/python3.9
        rm -r -f src/maple_alt
```

**Comment by christopher-vollmers** [comment]
I think there is only one instance of the new numpy being incompatible and
that is in the

bin/savitzky_golay.py

script.

        order = np.abs(np.int(order))

to

        order = np.abs(int(order))


should fix that.


It really shouldn't work if abpoa isn't found.
Are you running it on a new output folder? Are all the reads that make it
to the consensus file either 0 or 1 coverage?

Best,
Chris

**Comment by gordonrix** [comment]
Thanks! Yea that seems like it would be the better option. I have to edit that line and the line above it, I made a fork to do that I'll test it soon.

I'm attaching a plot that my pipeline makes from the C3POa outputs. The Y axis is showing the number of repeats in each read. It looks how I expect it to, theres a strong peak at ~3x concatemers as the DNA I loaded was mostly 3x concatemers. So I believe the program is running fine without abpoa. I do have pyabpoa installed, perhaps it's using that?
<img width="442" alt="image" src="https://github.com/christopher-vollmers/C3POa/assets/26627789/90cf87ca-a668-4027-8422-6049d3c13823">

**Comment by christopher-vollmers** [comment]
From the abpoa.messages file, it looks like it is trying to use abpoa. The new determine_consensus.py script doesn’t call pyaboa anymore. If abpoa doesn’t result in a prelim consensus, that function returns an empty string which then isn’t reported as a consensus file.I’m not sure what’s going on here. I would just try to run this again with a new output folder to see whether it definitely writes things out. On Jun 29, 2023, at 10:00 PM, Gordon Rix ***@***.***> wrote:﻿
Thanks! Yea that seems like it would be the better option. I have to edit that line and the line above it, I made a fork to do that I'll test it soon.
I'm attaching a plot that my pipeline makes from the C3POa outputs. The Y axis is showing the number of repeats in each read. It looks how I expect it to, theres a strong peak at ~3x concatemers as the DNA I loaded was mostly 3x concatemers. So I believe the program is running fine without abpoa. I do have pyabpoa installed, perhaps it's using that?

**Comment by gordonrix** [comment]
Ah, I know for a fact that the program that produces that abpoa message is producing this result. I am fully deleting the output directory before rerunning it. And I've gotten the old version working again after making those edits, and now I'm seeing that the previous results had more errors, something like 50% of consensus sequences had an error vs 75% now, which is more like what I remember it being. Should be smooth sailing for me here on out, thanks for the help!

**Comment by christopher-vollmers** [comment]
Very strange. I’ll do some testing on this to see what is happening. I compared outputs a lot going from pyabpoa to abpoa. If things are working output reads are >99% identical. I changed the consensus script a lot because there was some convoluted logic in there that was hard to maintain so maybe I did something weirdAnyway, good to hear it’s working on your end now.Best,ChrisOn Jun 29, 2023, at 10:25 PM, Gordon Rix ***@***.***> wrote:﻿
Ah, I know for a fact that the program that produces that abpoa message is producing this result. I am fully deleting the output directory before rerunning it. And I've gotten the old version working again after making those edits, and now I'm seeing that the previous results had more errors, something like 50% of consensus sequences had an error vs 75% now, which is more like what I remember it being. Should be smooth sailing for me here on out, thanks for the help!
